title: Welcome to My Web Page
author: Mahima
email: mahima.pal@velocitycloud.com
description: > # this means to ignore newlines until "baseurl:"
  Thia ia Mahima.
  I am enjoying this course provides by GitLAb. 
  Its very informative.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
